[package]
name = "rust-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
actix-rt = "2.5"
actix-cors = "0.6"
env_logger = "0.9"
log = "0.4"